[[redirects]]
  from = "/api/*"
  to = "https://eschoedeveloper.netlify.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://eschoedeveloper.netlify.app/auth/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200